modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="nogapsinyoitems"
version="${version}"
displayName="No Gaps In Yo Items"
description="Fixes visible gaps on 2D item models."
authors="Lumyrix"

[[dependencies.nogapsinyoitems]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="CLIENT"
